image: python:latest

#services:
#  - name: fallenbagel/jellyseerr:latest
#    alias: jellyseerr

build:
  stage: build
  script:
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - python --version
    - pwd
    - ls tests
    - python -m unittest