image: python:latest

#services:
#  - name: fallenbagel/jellyseerr:latest
#    alias: jellyseerr

test:
  script:
    - python --version
    - pip install -r requirements.txt
    - python -m unittest discover